### ISSUE TITLE
Supramatic P4 with HA

### ISSUE THREAD

**Issue by arpiska** [14yannick/esphome-hcpbridge#6]
Hello,

I'm lost in the abundance of information on the community [https://community.home-assistant.io/t/hormann-garage-door-via-mqtt/279938](url)
My engine is SupraMatic P4 and I would like to control it from HA.

I used ESP with RS485 like this: [https://github.com/Gifford47/HCPBridgeMqtt/blob/master/docs/Images/esp32.png](url)
Flashed HCPBridgeESP32 firmware. It works for a while then it crashes, I think error 4 or 7 appears on the display.

Could I use esphome-hcpbridge with my ESP-Wroom or I need to purchase custom board?

**Comment by 14yannick** [comment]
Yes the community page got out of control. No need of custom Board.
<img width="511" alt="image" src="https://github.com/user-attachments/assets/b9d242b6-4ffe-49f1-bf68-3d40e1651f68"> 
I personally use an m5Stack atom S3 with an M5Stack rs485 tail. If you where able to build a firmware for your your board on the mqtt project you will also be able to run the esphome build on it. Adjust the yaml with your board and pinout and you are ready to go.
I would suggest you to erase your ESP before flashing the esphome build.
`esptool.py --chip esp32 erase_flash`

**Comment by arpiska** [comment]
Thank you for your help!

I have installed this build: [https://github.com/Tysonpower/HCPBridgeMqtt_tynet?tab=readme-ov-file](url)
My board is ESP-WROOM-32 , with simple build ESP32
In HA added new ESPHome device and changed the yaml to your code: [https://github.com/14yannick/esphome-hcpbridge](url)
Changed the pin to 16rx / 17tx and board to nodemcu-32s.

Now I need help how to pair it with the phisical device?

**Comment by 14yannick** [comment]
Could you send me a picture of your board because I'm not sure if you have a nodemcu-32s.
You mean how to upload the firmware to your esp or how to connect it your motor?

**Comment by arpiska** [comment]
No, I the firmware is uploaded, the mqtt is configured on the board with username and pass.
In HA how to add the board step by set?
I need to add new ESPHome device with the yaml code attached?

![20241030_130230_cr](https://github.com/user-attachments/assets/b4cafd49-8b4f-4fb6-8fca-61907798b4e7)
[hormann_gate.zip](https://github.com/user-attachments/files/17584416/hormann_gate.zip)

**Comment by 14yannick** [comment]
ok your yaml looks not complete. At least you should add the wifi Component, OTA and integration component like API.  Your yaml will the look like this.
```YAML
substitutions:
  name: "hcpbridge"
  friendly_name: "Garage Door"
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  libraries:
    - emelianov/modbus-esp8266 # Required for communication with the modbus
  platformio_options:
    board_build.f_cpu: 240000000L
    board_build.flash_mode: qio
    monitor_speed: 9600
    monitor_filters: esp32_exception_decoder
    lib_ldf_mode: deep+
    # board_build.f_flash: 40000000L

external_components:
    source: github://14yannick/esphome-hcpbridge
    refresh: 0s # Ensure you always get the latest version

esp32:
  board: nodemcu-32s #adafruit_feather_esp32s3 #set your board
  framework:
    type: arduino

hcpbridge:
  id: hcpbridge_id
  rx_pin: 16 # optional, default=18
  tx_pin: 17 # optional, default=17
  #rts_pin : 1 # optional RTS pin to use if hardware automatic control flow is not available.

cover:
  - platform: hcpbridge
    name: ${friendly_name}
    device_class: garage
    id: garagedoor_cover

#here you need to define with which Integration you will include it in HA I suggest the native API
#alternatively you could also integrate it with MQTT
api:
  encryption:
    key: !secret api_key
  services:
    - service: go_to_open
      then:
        - lambda: |-
            id(garagedoor_cover).on_go_to_open();
    - service: go_to_close
      then:
        - lambda: |-
            id(garagedoor_cover).on_go_to_close();
    - service: go_to_half
      then:
        - lambda: |-
            id(garagedoor_cover).on_go_to_half();
    - service: go_to_vent
      then:
        - lambda: |-
            id(garagedoor_cover).on_go_to_vent();
    - service: toggle
      then:
        - cover.toggle: garagedoor_cover

#Optional if you want to control you door without Home Assistant directly in browser
#web_server:
#  port: 80
#  auth:
#    username: !secret web_username
#    password: !secret web_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  level: DEBUG
  baud_rate: 9600

# Example configuration entry
ota:
  - platform: esphome
```
Check this [page ](https://esphome.io/guides/getting_started_hassio.html) you need first to create a binary with this yaml easiest by Installing ESPHome Dashboard (see documentation above).  once you have it Upload it to the device most of the time by connecting to my computer and got to [this ](https://web.esphome.io/) webpage.
 Then you can use the esphome integration to find the device in your network and include in HA.
You have a link to add the Dashboard and the integration in the attached documentation.

**Comment by arpiska** [comment]
Thank you,  moved forward a "few steps"!
Created bin file via ESPHome Web and uploaded firmware to ESP.
It is connected to HA, but it can't connect with the SupraMatic.
RXD lights on the RS485 board, but TXD won't.

**Comment by 14yannick** [comment]
first guess would be that something is wrong with the pin definition of RX and TX or that your wiring is not good.

**Comment by 14yannick** [comment]
Ok I just took my first pcb I used at the beginning.
<img src="https://github.com/user-attachments/assets/ecf23486-b688-4cb4-8c98-bdbdfd4ffa9b" width="500"> 
You can find the wiring [here](https://github.com/14yannick/HCPBridgeMqtt/blob/master/PCB/ESP32-DivKitC%20Pro%20LAYOUT.png). 
I Flashed with this yaml. and it worked.  Maybe the problem came from your board I stopped the use the really chip boards as I found them not as reliable as the genuine one. 
```YAML
substitutions:
  name: "devkitc"
  friendly_name: "devkitc"
  connection_state: "${name} Connected"
  relay_name: "${friendly_name} Relay state"
  light: "${friendly_name} Light"
  btn_vent: "${friendly_name} Vent" 
  btn_half: "${friendly_name} Half" 
  btn_impulse: "${friendly_name} Impulse" 
  sen_txt: "${friendly_name} State" 
  sw_vent: "${friendly_name} Venting" 
  sw_half: "${friendly_name} Open Half" 

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  libraries:
    - emelianov/modbus-esp8266 # Required for communication with the modbus
  platformio_options:
    board_build.f_cpu: 240000000L
    board_build.flash_mode: qio
    monitor_speed: 9600
    monitor_filters: esp32_exception_decoder
    lib_ldf_mode: deep+
    # board_build.f_flash: 40000000L

external_components:
    source: github://14yannick/esphome-hcpbridge
    refresh: 0s # Ensure you always get the latest version

esp32:
  board: esp32dev
  framework:
    type: arduino

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


hcpbridge:
  id: hcpbridge_id
  rx_pin: 16 # optional, default=18
  tx_pin: 17 # optional, default=17
  #rts_pin : 1 # optional RTS pin to use if hardware automatic control flow is not available.

cover:
  - platform: hcpbridge
    name: ${friendly_name}
    device_class: garage
    id: garagedoor_cover


binary_sensor:
  - platform: hcpbridge
    is_connected:
      name: "${connection_state}"
      id: sensor_connected
    relay_state:
      name: "${relay_name}"
      id: sensor_relay
      #on_state:
      #create your automation based on Garage Door Relay state

output:
  - platform: hcpbridge
    id: output_light

light:
  - platform: hcpbridge
    id: gd_light
    output: output_light
    name: ${light}

button:
  - platform: hcpbridge
    vent_button:
      id: button_vent
      name: "${btn_vent}"
    impulse_button:
      id: button_impulse
      name: "${btn_impulse}"
    half_button:
      id: button_half
      name: "${btn_half}"

text_sensor:
  - platform: hcpbridge
    id: sensor_templ_state
    name: "${sen_txt}"
#    filters:
#      - substitute:
#        - "Opening -> your text"
#        - "Move venting -> your text"
#        - "Move half -> your text"
#        - "Closing -> your text"
#        - "Open -> your text"
#        - "Closed -> your text"
#        - "Stopped -> your text"
#        - "Half open -> your text"
#        - "Venting -> your text"
#        - "Unknown -> your text"

switch:
  - platform: hcpbridge
    vent_switch:
      id: switch_vent
      name: "${sw_vent}"
      restore_mode: disabled
    half_switch:
      id: half_switch
      name: "${sw_half}"
      restore_mode: disabled

#here you need to define with which Integration you will include it in HA I suggest the native API
#alternatively you could also integrate it with MQTT
api:
  encryption:
    key: !secret api_key
  services:
    - service: go_to_open
      then:
        - lambda: |-
            id(garagedoor_cover).on_go_to_open();
    - service: go_to_close
      then:
        - lambda: |-
            id(garagedoor_cover).on_go_to_close();
    - service: go_to_half
      then:
        - lambda: |-
            id(garagedoor_cover).on_go_to_half();
    - service: go_to_vent
      then:
        - lambda: |-
            id(garagedoor_cover).on_go_to_vent();
    - service: toggle
      then:
        - cover.toggle: garagedoor_cover


# Enable logging
logger:
  level: DEBUG
  baud_rate: 9600

```
